version: '3.9'
services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    environment:
      - "MSSQL_SA_PASSWORD=Password--"
    ports:
      - 1433:1433
    volumes:
      - "sql:/var/opt/mssql:rw"
      - ./data:/data
  init:
    network_mode: host
    build:
      context: .
      dockerfile: docker/init/Dockerfile
    environment:
      - "MSSQL_SA_PASSWORD=Password--"
      - "DATABASE_NAME=example"
      - "DATABASE_FILE=example.bak"
volumes:
  sql:
