version: '3.9'
services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    environment:
      MSSQL_SA_PASSWORD: "${SA_PASSWORD:?password}"
    ports:
      - 1433:1433
    volumes:
      - "sql:/var/opt/mssql:rw"
      - ./data:/data
  init:
    network_mode: host
    build:
      context: .
      dockerfile: docker/init/Dockerfile
    environment:
      MSSQL_SA_PASSWORD: "${SA_PASSWORD:?password}"
      DATABASE_NAME: "${DATABASE_NAME:?dbname}"
      DATABASE_FILE: "${DATABASE_FILE:?dbfile}"
volumes:
  sql:
